//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCGL.DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.UI;
using System.Web;


namespace SCGL.BAL
{
    
    
    public class InvoiceDutiesDesc : DAL_InvoiceDutiesDesc
    {
        
        #region Private Properties
        // ======================== Properties ========================
        private int _InvoiceDutiesDescID;

        private string _InvoiceDutiesDescription;
        
        private DateTime _CreatedDate;

        private bool _IsInvoiceDutiesDescExist;

        #endregion
        
        #region Constructor
        public InvoiceDutiesDesc()
        {
        }
        #endregion
        
        #region Property Method
        // ======================= Property Method ======================
        public int InvoiceDutiesDescID
        {
            get
            {
                return this._InvoiceDutiesDescID;
            }
            set
            {
                this._InvoiceDutiesDescID = value;
            }
        }

        public string InvoiceDutiesDescription
        {
            get
            {
                return this._InvoiceDutiesDescription;
            }
            set
            {
                this._InvoiceDutiesDescription = value;
            }
        }
        
        public DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this._CreatedDate = value;
            }
        }

        public bool IsInvoiceDutiesDescExist
        {
            get
            {
                return this._IsInvoiceDutiesDescExist;
            }
            set
            {
                this._IsInvoiceDutiesDescExist = value;
            }
        }
        #endregion
        
        #region Public Method
        // =========================== Public Method =========================
        public override int Create(InvoiceDutiesDesc p)
        {
            try
            {
                return base.Create(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override InvoiceDutiesDesc Read(int p)
        {
            try
            {
                return base.Read(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override DataTable ReadDataTable()
        {
            try
            {
                return base.ReadDataTable();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override List<InvoiceDutiesDesc> Read()
        {
            try
            {
                return base.Read();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override bool Update(InvoiceDutiesDesc p)
        {
            SCGL_Session SBO = (SCGL_Session)System.Web.HttpContext.Current.Session["SessionBO"];
            if (SBO.Can_Update == true)
            {
                try
                {
                    return base.Update(p);
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                JQ.showStatusMsg((Page)(HttpContext.Current.Handler), "3", "User not Allowed to Update Record");
                return false;
            }
        }
        
        public override bool Delete(int p)
        {
            try
            {
                return base.Delete(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public bool Delete(InvoiceDutiesDesc p)
        {
             SCGL_Session SBO = (SCGL_Session)System.Web.HttpContext.Current.Session["SessionBO"];
             if (SBO.Can_Delete == true)
             {
                 try
                 {
                     return base.Delete(p.InvoiceDutiesDescID);
                 }
                 catch (Exception ex)
                 {
                     throw ex;
                 }
             }
             else
             {
                 JQ.showStatusMsg((Page)(HttpContext.Current.Handler), "3", "User not Allowed to Delete Record");
                 return false;
             }
        }
        #endregion
    }
}
