//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using SCGL.DAL;


namespace SCGL.BAL
{
    
    
    public class InvoiceDetail : DAL_InvoiceDetail
    {
        
        #region Private Properties
        // ======================== Properties ========================
        private int _InvoiceDetailID;
        
        private int _InvoiceID;
        
        private int _InvoiceDescID;
        
        private string _Number;

        private string _Remarks;

        private string _Date;
        
        private decimal _ByParty;
        
        private decimal _ByUS;
        #endregion
        
        #region Constructor
        public InvoiceDetail()
        {
        }
        #endregion
        
        #region Property Method
        // ======================= Property Method ======================
        public int InvoiceDetailID
        {
            get
            {
                return this._InvoiceDetailID;
            }
            set
            {
                this._InvoiceDetailID = value;
            }
        }
        
        public int InvoiceID
        {
            get
            {
                return this._InvoiceID;
            }
            set
            {
                this._InvoiceID = value;
            }
        }
        
        public int InvoiceDescID
        {
            get
            {
                return this._InvoiceDescID;
            }
            set
            {
                this._InvoiceDescID = value;
            }
        }
        
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this._Number = value;
            }
        }

        public string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                this._Remarks = value;
            }
        }

        public string Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this._Date = value;
            }
        }
        
        public decimal ByParty
        {
            get
            {
                return this._ByParty;
            }
            set
            {
                this._ByParty = value;
            }
        }
        
        public decimal ByUS
        {
            get
            {
                return this._ByUS;
            }
            set
            {
                this._ByUS = value;
            }
        }
        #endregion
        
        #region Public Method
        // =========================== Public Method =========================
        public override int Create(InvoiceDetail p)
        {
            try
            {
                return base.Create(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override InvoiceDetail Read(int p)
        {
            try
            {
                return base.Read(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override DataTable ReadDataTable()
        {
            try
            {
                return base.ReadDataTable();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override List<InvoiceDetail> Read()
        {
            try
            {
                return base.Read();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public override List<InvoiceDetail> ReadByInvoiceID(int InvoiceID)
        {
            try
            {
                return base.ReadByInvoiceID(InvoiceID);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override bool Update(InvoiceDetail p)
        {
            try
            {
                return base.Update(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public override bool Delete(int p)
        {
            try
            {
                return base.Delete(p);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
    }
}
