//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCGL.BAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using SW.SW_Common;
using SQLHelper;

namespace SCGL.DAL
{
    
    
    public class DAL_InvoiceDesc
    {
        
        #region ConnectionStringuctor
        public DAL_InvoiceDesc()
        {
        }
        #endregion
        
        #region Public Method
        // =========================== Public Method =========================
        public virtual int Create(InvoiceDesc p)
        {
            try
            {
                SqlParameter[] SqlParam = new SqlParameter[] {
                        new SqlParameter("InvoiceDescription", p.InvoiceDescription),
                        new SqlParameter("CreatedDate", p.CreatedDate)};
                return Convert.ToInt32(SqlHelper.ExecuteScalar(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Insert", SqlParam));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public virtual InvoiceDesc Read(int p)
        {
            try
            {
                SqlParameter SqlParam = new SqlParameter("InvoiceDescID", p);
                InvoiceDesc obj = new InvoiceDesc();
                using (SqlDataReader dr = SqlHelper.ExecuteReader(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Read", SqlParam))
                {
                obj = DataReader(dr);
                }
                return obj;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public virtual DataTable ReadDataTable()
        {
            try
            {
                return SqlHelper.ExecuteDataset(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Read").Tables[0];
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public virtual List<InvoiceDesc> Read()
        {
            try
            {
                List<InvoiceDesc> obj = new List<InvoiceDesc>();
                using (SqlDataReader dr = SqlHelper.ExecuteReader(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Read"))
                {
                obj = ListDataReader(dr);
                }
                return obj;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public virtual bool Update(InvoiceDesc p)
        {
            try
            {
                SqlParameter[] SqlParam = new SqlParameter[] {
                        new SqlParameter("InvoiceDescID", p.InvoiceDescID),
                        new SqlParameter("InvoiceDescription", p.InvoiceDescription)};
                int i = SqlHelper.ExecuteNonQuery(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Update", SqlParam);
                return i >= 1;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        public virtual bool Delete(int p)
        {
            try
            {
                SqlParameter SqlParam = new SqlParameter("InvoiceDescID", p);
                int i = SqlHelper.ExecuteNonQuery(ConnectionString.PSMS, "VT_SP_InvoiceDesc_Delete", SqlParam);
                return i >= 1;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion
        
        #region Helper Method
        // =========================== Helper Method =========================
        private InvoiceDesc DataReader(SqlDataReader dr)
        {
            InvoiceDesc obj = new InvoiceDesc();
            try
            {
                if (dr.Read())
                {
                    obj.InvoiceDescID = SCGL_Common.CheckInt(dr["InvoiceDescID"]);
                    obj.InvoiceDescription = SCGL_Common.CheckString(dr["InvoiceDescription"]);
                    obj.CreatedDate = SCGL_Common.CheckDateTime(dr["CreatedDate"]);
                    obj.IsInvoiceDescExist = SCGL_Common.CheckBoolean(dr["IsInvoiceDescExist"]);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return obj;
        }
        
        private List<InvoiceDesc> ListDataReader(SqlDataReader dr)
        {
            List<InvoiceDesc> objList = new List<InvoiceDesc>();
            try
            {
               while(dr.Read())
               {
                InvoiceDesc obj = new InvoiceDesc();
                obj.InvoiceDescID = SCGL_Common.CheckInt(dr["InvoiceDescID"]);
                obj.InvoiceDescription = SCGL_Common.CheckString(dr["InvoiceDescription"]);
                obj.CreatedDate = SCGL_Common.CheckDateTime(dr["CreatedDate"]);
                obj.IsInvoiceDescExist = SCGL_Common.CheckBoolean(dr["IsInvoiceDescExist"]);
                objList.Add(obj);
               }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return objList;
        }
        #endregion
    }
}
